/* seedNotes.ts - As notas de exemplo do primeiro uso.
 *
 * Nenhuma delas usa marcacao de link: quem liga e o motor (lib/graphify.ts).
 * A nota "Como o Dott conecta suas notas" cita as outras pelo nome de proposito,
 * pra a Constelacao ja nascer com conexoes ACHADAS de verdade.
 */
import type { Note } from '../store'

export const SEED_NOTES: Note[] = [
  {
    id: 'n1',
    title: 'Bem-vindo ao Dott',
    date: '10/06/2026',
    updatedAt: '10/06/2026',
    img: false,
    folderId: 'start',
    tags: ['tutorial', 'inicio'],
    body: [
      '# Bem-vindo ao Dott',
      '',
      'Dott é o seu segundo cérebro. Tudo que você pensa, captura e organiza vira arquivo de texto seu, e você escolhe onde ele mora.',
      '',
      '## Como funciona',
      '',
      '- **Inbox** (painel esquerdo): capture qualquer coisa sem pensar. Textos, links, ideias, imagens.',
      '- **PARA** (centro): organize em Projetos, Áreas, Recursos e Arquivo.',
      '- **Notas**: escreva em markdown. O Dott liga as notas sozinho.',
      '- **Widget**: pressione `Ctrl+Shift+Space` em qualquer app para capturar algo rapidinho.',
      '',
      'Comece pela pasta **Comece aqui** e explore as outras notas do tutorial.',
    ].join('\n'),
  },
  {
    id: 'n2',
    title: 'O método PARA',
    date: '10/06/2026',
    updatedAt: '10/06/2026',
    img: false,
    folderId: 'start',
    tags: ['tutorial', 'para', 'metodo'],
    body: [
      '# O método PARA',
      '',
      'PARA é um sistema criado por Tiago Forte para organizar qualquer tipo de informação digital.',
      '',
      '## Os 4 quadrantes',
      '',
      '- **Projetos**: coisas com prazo e resultado esperado. Ex.: "Lançar site até julho".',
      '- **Áreas**: responsabilidades contínuas sem prazo. Ex.: "Saúde", "Finanças".',
      '- **Recursos**: referências e materiais que você quer guardar. Ex.: "Leituras", "Modelos".',
      '- **Arquivo**: tudo que já foi útil mas está inativo. Não jogue fora, arquive.',
      '',
      '## Regra de ouro',
      '',
      'Um item pertence ao quadrante mais **acionável**. Projeto, Área, Recurso, Arquivo, nessa ordem.',
      '',
      'Veja também: Bem-vindo ao Dott.',
    ].join('\n'),
  },
  {
    id: 'n3',
    title: 'Como o Dott conecta suas notas',
    date: '10/06/2026',
    updatedAt: '10/06/2026',
    img: false,
    folderId: 'start',
    tags: ['tutorial', 'conexoes', 'constelacao'],
    body: [
      '# Como o Dott conecta suas notas',
      '',
      'Você não precisa ligar nada à mão. Escreva do seu jeito: o Dott lê o que você escreveu e monta as conexões sozinho, na sua máquina, sem internet e sem inteligência artificial.',
      '',
      '## De onde vem cada conexão',
      '',
      '- **Citou pelo nome**: se você escrever o título de outra nota no meio do texto, as duas se ligam na hora. É o caso desta nota com O método PARA e com Captura pelo widget.',
      '- **Mesma etiqueta**: notas que carregam a mesma #etiqueta ficam próximas.',
      '- **Mesmo assunto**: quando duas notas repetem as mesmas palavras raras, o Dott percebe que elas falam da mesma coisa, mesmo sem nenhuma citar a outra.',
      '',
      '## Sempre honesto',
      '',
      'Cada conexão diz de onde veio. **Achada** quer dizer que estava escrito no texto. **Inferida** quer dizer que o Dott deduziu por semelhança. Você nunca vê uma ligação sem saber o motivo.',
      '',
      '## Onde olhar',
      '',
      'Abra a **Constelação** na barra do topo para ver o mapa inteiro, agrupado por tema. No pé de cada nota ficam as notas conectadas a ela.',
    ].join('\n'),
  },
  {
    id: 'n4',
    title: 'Captura pelo widget',
    date: '10/06/2026',
    updatedAt: '10/06/2026',
    img: false,
    folderId: 'start',
    tags: ['tutorial', 'widget', 'captura'],
    body: [
      '# Captura pelo widget',
      '',
      'O widget do Dott é um orb flutuante que fica disponível **em qualquer aplicativo**.',
      '',
      '## Como usar',
      '',
      '1. Pressione `Ctrl+Shift+Space` em qualquer lugar.',
      '2. O widget aparece na tela.',
      '3. Digite sua ideia, cole um link, ou escreva uma tarefa.',
      '4. Pressione Enter, o card vai direto para o seu Inbox.',
      '',
      '## Por que importa',
      '',
      'Captura sem fricção significa que você não perde nenhuma ideia esperando abrir o app. Capture agora, processe depois.',
      '',
      'Veja como processar: Processe seu inbox.',
    ].join('\n'),
  },
  {
    id: 'n5',
    title: 'Processe seu inbox',
    date: '10/06/2026',
    updatedAt: '10/06/2026',
    img: false,
    folderId: 'start',
    tags: ['tutorial', 'inbox', 'gtd'],
    body: [
      '# Processe seu inbox',
      '',
      'O Inbox não é um destino, é uma caixa de entrada temporária. Processe regularmente.',
      '',
      '## Como processar um card',
      '',
      '**Opção 1, arrastar:** arraste o card do Inbox até uma pasta no board. O card vira nota automaticamente.',
      '',
      '**Opção 2, deletar:** se não serve para nada, delete. Sem culpa.',
      '',
      '## Frequência recomendada',
      '',
      '- Inbox cheio (10 cards)? Processe antes de capturar mais.',
      '- Rotina ideal: revise o inbox uma vez por dia, como e-mail.',
      '',
      'Veja também: Bem-vindo ao Dott.',
    ].join('\n'),
  },
]
