/* filerobotConfig.ts — tema escuro e traducao pt-BR do Filerobot Image Editor
 * (TASK-407), separados do componente pra nao inflar ImageViewer.tsx.
 *
 * Tema: espelha os MESMOS hex que ImageViewer.tsx ja usava pro markerjs2
 * (tokens.css, tema escuro: --surface #141417, --surface2 #1a1a1e,
 * --surface3 #222228, --fg #e8e8ec, --fg2 #aeaec2, --fg3 #8c8ca6,
 * --border #26262c, --border2 #2e2e36, --accent #e05a38, --danger #e04040,
 * --warn #d98c3a, --success #3db37a). O Filerobot nao le CSS var (o tema e
 * um objeto JS resolvido uma vez), entao os hex ficam hardcoded aqui - mesma
 * convencao que o codigo anterior ja usava pro markerjs2, so hex duplicado
 * do token, nao um valor novo.
 *
 * Traducao: NUNCA usar `useBackendTranslations` (default `true` no pacote -
 * ver MEDIDO em node_modules/react-filerobot-image-editor/lib/context/
 * defaultConfig.js e lib/hooks/useLoadMainSource.js). Com ele ligado, o
 * editor faz XHR pra https://i18n.ultrafast.io e POST pra
 * https://neo.wordplex.io TODA VEZ que abre - quebra o invariante 100%
 * offline mesmo bloqueado pela CSP (connect-src nao inclui esses hosts).
 * ImageViewer.tsx passa `useBackendTranslations={false}` e usa este objeto
 * estatico local em vez disso - zero rede.
 */

/** Paleta minima: so as chaves que aparecem nas abas habilitadas
 *  (Ajustar/Recortar/Girar, Anotar/Desenhar/Texto/Formas, Filtros, Ajuste
 *  fino). O tipo `ThemeOverride` da lib e `Partial<...>` - nao precisa
 *  cobrir as ~130 chaves da paleta default. */
export const FILEROBOT_DARK_THEME = {
  palette: {
    'txt-primary': '#e8e8ec',
    'txt-secondary': '#aeaec2',
    'txt-secondary-invert': '#e8e8ec',
    'txt-placeholder': '#8c8ca6',
    'bg-primary': '#1a1a1e',
    'bg-primary-hover': '#222228',
    'bg-primary-active': '#222228',
    'bg-secondary': '#141417',
    'bg-stateless': '#141417',
    'bg-active': '#222228',
    'bg-hover': '#222228',
    'accent-primary': '#e05a38',
    'accent-primary-hover': '#e05a38',
    'accent-primary-active': '#e05a38',
    'accent-stateless': '#e05a38',
    'icon-primary': '#aeaec2',
    'icons-secondary': '#8c8ca6',
    'icons-primary-hover': '#e8e8ec',
    'icons-secondary-hover': '#aeaec2',
    'borders-primary': '#2e2e36',
    'borders-secondary': '#26262c',
    'borders-strong': '#2e2e36',
    'borders-item': '#26262c',
    'btn-primary-text': '#e8e8ec',
    'btn-secondary-text': '#e8e8ec',
    'btn-disabled-text': '#8c8ca6',
    error: '#e04040',
    warning: '#d98c3a',
    success: '#3db37a',
  },
} as const

/** Traducao completa das chaves de `defaultTranslations` (lib da versao
 *  5.0.1) pra pt-BR. Estatico - nunca busca do backend (ver header). */
export const FILEROBOT_PT_BR_TRANSLATIONS = {
  name: 'Nome',
  save: 'Salvar',
  saveAs: 'Salvar como',
  back: 'Voltar',
  loading: 'Carregando...',
  resetOperations: 'Repor/apagar todas as operações',
  changesLoseWarningHint: 'Se você clicar em "Repor" suas alterações serão perdidas. Deseja continuar?',
  discardChangesWarningHint: 'Se você fechar, a última alteração não será salva.',
  cancel: 'Cancelar',
  apply: 'Aplicar',
  warning: 'Aviso',
  confirm: 'Confirmar',
  discardChanges: 'Descartar alterações',
  undoTitle: 'Desfazer última operação',
  redoTitle: 'Refazer última operação',
  showImageTitle: 'Mostrar imagem original',
  zoomInTitle: 'Aproximar',
  zoomOutTitle: 'Afastar',
  toggleZoomMenuTitle: 'Alternar menu de zoom',
  adjustTab: 'Ajustar',
  finetuneTab: 'Ajuste fino',
  filtersTab: 'Filtros',
  watermarkTab: "Marca d'água",
  annotateTabLabel: 'Desenhar',
  resize: 'Redimensionar',
  resizeTab: 'Redimensionar',
  imageName: 'Nome da imagem',
  invalidImageError: 'Imagem inválida.',
  uploadImageError: 'Erro ao enviar a imagem.',
  areNotImages: 'não são imagens',
  isNotImage: 'não é imagem',
  toBeUploaded: 'para enviar',
  cropTool: 'Recortar',
  original: 'Original',
  custom: 'Personalizado',
  square: 'Quadrado',
  landscape: 'Paisagem',
  portrait: 'Retrato',
  ellipse: 'Elipse',
  classicTv: 'TV clássica',
  cinemascope: 'Cinemascópio',
  arrowTool: 'Seta',
  blurTool: 'Desfoque',
  brightnessTool: 'Brilho',
  contrastTool: 'Contraste',
  ellipseTool: 'Elipse',
  unFlipX: 'Desfazer espelhar X',
  flipX: 'Espelhar X',
  unFlipY: 'Desfazer espelhar Y',
  flipY: 'Espelhar Y',
  hsvTool: 'HSV',
  hue: 'Matiz',
  brightness: 'Brilho',
  saturation: 'Saturação',
  value: 'Valor',
  imageTool: 'Imagem',
  importing: 'Importando...',
  addImage: '+ Adicionar imagem',
  uploadImage: 'Enviar imagem',
  fromGallery: 'Da galeria',
  lineTool: 'Linha',
  penTool: 'Caneta',
  polygonTool: 'Polígono',
  sides: 'Lados',
  rectangleTool: 'Retângulo',
  cornerRadius: 'Raio do canto',
  resizeWidthTitle: 'Largura em pixels',
  resizeHeightTitle: 'Altura em pixels',
  toggleRatioLockTitle: 'Alternar trava de proporção',
  resetSize: 'Repor tamanho original',
  rotateTool: 'Girar',
  textTool: 'Texto',
  textSpacings: 'Espaçamento de texto',
  textAlignment: 'Alinhamento de texto',
  fontFamily: 'Fonte',
  size: 'Tamanho',
  letterSpacing: 'Espaçamento entre letras',
  lineHeight: 'Altura da linha',
  warmthTool: 'Temperatura',
  addWatermark: "+ Adicionar marca d'água",
  addTextWatermark: "+ Adicionar marca d'água de texto",
  addWatermarkTitle: "Escolha o tipo de marca d'água",
  uploadWatermark: "Enviar marca d'água",
  addWatermarkAsText: 'Adicionar como texto',
  padding: 'Espaçamento',
  paddings: 'Espaçamentos',
  shadow: 'Sombra',
  horizontal: 'Horizontal',
  vertical: 'Vertical',
  blur: 'Desfoque',
  opacity: 'Opacidade',
  transparency: 'Transparência',
  position: 'Posição',
  stroke: 'Contorno',
  saveAsModalTitle: 'Salvar como',
  extension: 'Extensão',
  format: 'Formato',
  nameIsRequired: 'Nome é obrigatório.',
  quality: 'Qualidade',
  imageDimensionsHoverTitle: 'Tamanho salvo (largura x altura)',
  cropSizeLowerThanResizedWarning: 'A área de recorte selecionada é menor que o redimensionamento aplicado, o que pode reduzir a qualidade.',
  actualSize: 'Tamanho real (100%)',
  fitSize: 'Ajustar tamanho',
  addImageTitle: 'Selecione a imagem para adicionar...',
  mutualizedFailedToLoadImg: 'Falha ao carregar a imagem.',
  tabsMenu: 'Menu',
  download: 'Baixar',
  width: 'Largura',
  height: 'Altura',
  plus: '+',
  cropItemNoEffect: 'Sem pré-visualização disponível para este recorte',
  px: 'px',
}
